// source: content/v1/content.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.paralympics.content.v1.ContentModule', null, global);
goog.exportSymbol('proto.paralympics.content.v1.Image', null, global);
goog.exportSymbol('proto.paralympics.content.v1.ImageCrop', null, global);
goog.exportSymbol('proto.paralympics.content.v1.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.paralympics.content.v1.ContentModule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.paralympics.content.v1.ContentModule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.paralympics.content.v1.ContentModule.displayName = 'proto.paralympics.content.v1.ContentModule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.paralympics.content.v1.ImageCrop = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.paralympics.content.v1.ImageCrop, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.paralympics.content.v1.ImageCrop.displayName = 'proto.paralympics.content.v1.ImageCrop';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.paralympics.content.v1.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.paralympics.content.v1.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.paralympics.content.v1.Image.displayName = 'proto.paralympics.content.v1.Image';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.paralympics.content.v1.ContentModule.prototype.toObject = function(opt_includeInstance) {
  return proto.paralympics.content.v1.ContentModule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.paralympics.content.v1.ContentModule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.ContentModule.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    order: jspb.Message.getFieldWithDefault(msg, 2, 0),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    text: jspb.Message.getFieldWithDefault(msg, 4, ""),
    textHtml: jspb.Message.getFieldWithDefault(msg, 5, ""),
    chapterHeading: jspb.Message.getFieldWithDefault(msg, 6, ""),
    image: (f = msg.getImage()) && proto.paralympics.content.v1.Image.toObject(includeInstance, f),
    imageAlt: jspb.Message.getFieldWithDefault(msg, 8, ""),
    imageCaption: jspb.Message.getFieldWithDefault(msg, 9, ""),
    imageFullScreen: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    quoteText: jspb.Message.getFieldWithDefault(msg, 11, ""),
    quoteAuthor: jspb.Message.getFieldWithDefault(msg, 12, ""),
    highlightText: jspb.Message.getFieldWithDefault(msg, 13, ""),
    videoUrl: jspb.Message.getFieldWithDefault(msg, 14, ""),
    videoCaption: jspb.Message.getFieldWithDefault(msg, 15, ""),
    videoCover: (f = msg.getVideoCover()) && proto.paralympics.content.v1.Image.toObject(includeInstance, f),
    videoTitle: jspb.Message.getFieldWithDefault(msg, 17, ""),
    dropdownTitle: jspb.Message.getFieldWithDefault(msg, 18, ""),
    achievementGame: jspb.Message.getFieldWithDefault(msg, 19, ""),
    achievementGold: jspb.Message.getFieldWithDefault(msg, 20, 0),
    achievementSilver: jspb.Message.getFieldWithDefault(msg, 21, 0),
    achievementBronze: jspb.Message.getFieldWithDefault(msg, 22, 0),
    title: jspb.Message.getFieldWithDefault(msg, 23, ""),
    subTitle: jspb.Message.getFieldWithDefault(msg, 24, ""),
    link: jspb.Message.getFieldWithDefault(msg, 25, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.paralympics.content.v1.ContentModule}
 */
proto.paralympics.content.v1.ContentModule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.paralympics.content.v1.ContentModule;
  return proto.paralympics.content.v1.ContentModule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.paralympics.content.v1.ContentModule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.paralympics.content.v1.ContentModule}
 */
proto.paralympics.content.v1.ContentModule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOrder(value);
      break;
    case 3:
      var value = /** @type {!proto.paralympics.content.v1.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextHtml(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setChapterHeading(value);
      break;
    case 7:
      var value = new proto.paralympics.content.v1.Image;
      reader.readMessage(value,proto.paralympics.content.v1.Image.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageAlt(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCaption(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setImageFullScreen(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuoteText(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuoteAuthor(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setHighlightText(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideoUrl(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideoCaption(value);
      break;
    case 16:
      var value = new proto.paralympics.content.v1.Image;
      reader.readMessage(value,proto.paralympics.content.v1.Image.deserializeBinaryFromReader);
      msg.setVideoCover(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideoTitle(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setDropdownTitle(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setAchievementGame(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAchievementGold(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAchievementSilver(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAchievementBronze(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubTitle(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setLink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.paralympics.content.v1.ContentModule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.paralympics.content.v1.ContentModule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.paralympics.content.v1.ContentModule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.ContentModule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrder();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTextHtml();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChapterHeading();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.paralympics.content.v1.Image.serializeBinaryToWriter
    );
  }
  f = message.getImageAlt();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getImageCaption();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getImageFullScreen();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getQuoteText();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getQuoteAuthor();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getHighlightText();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getVideoUrl();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getVideoCaption();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getVideoCover();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.paralympics.content.v1.Image.serializeBinaryToWriter
    );
  }
  f = message.getVideoTitle();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getDropdownTitle();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getAchievementGame();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getAchievementGold();
  if (f !== 0) {
    writer.writeInt64(
      20,
      f
    );
  }
  f = message.getAchievementSilver();
  if (f !== 0) {
    writer.writeInt64(
      21,
      f
    );
  }
  f = message.getAchievementBronze();
  if (f !== 0) {
    writer.writeInt64(
      22,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getSubTitle();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getLink();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 order = 2;
 * @return {number}
 */
proto.paralympics.content.v1.ContentModule.prototype.getOrder = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ContentModule.prototype.setOrder = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Type type = 3;
 * @return {!proto.paralympics.content.v1.Type}
 */
proto.paralympics.content.v1.ContentModule.prototype.getType = function() {
  return /** @type {!proto.paralympics.content.v1.Type} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.paralympics.content.v1.Type} value */
proto.paralympics.content.v1.ContentModule.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string text = 4;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setText = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string text_html = 5;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getTextHtml = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setTextHtml = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string chapter_heading = 6;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getChapterHeading = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setChapterHeading = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Image image = 7;
 * @return {?proto.paralympics.content.v1.Image}
 */
proto.paralympics.content.v1.ContentModule.prototype.getImage = function() {
  return /** @type{?proto.paralympics.content.v1.Image} */ (
    jspb.Message.getWrapperField(this, proto.paralympics.content.v1.Image, 7));
};


/** @param {?proto.paralympics.content.v1.Image|undefined} value */
proto.paralympics.content.v1.ContentModule.prototype.setImage = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.paralympics.content.v1.ContentModule.prototype.clearImage = function() {
  this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.paralympics.content.v1.ContentModule.prototype.hasImage = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string image_alt = 8;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getImageAlt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setImageAlt = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string image_caption = 9;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getImageCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setImageCaption = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional bool image_full_screen = 10;
 * @return {boolean}
 */
proto.paralympics.content.v1.ContentModule.prototype.getImageFullScreen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/** @param {boolean} value */
proto.paralympics.content.v1.ContentModule.prototype.setImageFullScreen = function(value) {
  jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional string quote_text = 11;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getQuoteText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setQuoteText = function(value) {
  jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string quote_author = 12;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getQuoteAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setQuoteAuthor = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string highlight_text = 13;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getHighlightText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setHighlightText = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string video_url = 14;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getVideoUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setVideoUrl = function(value) {
  jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string video_caption = 15;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getVideoCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setVideoCaption = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional Image video_cover = 16;
 * @return {?proto.paralympics.content.v1.Image}
 */
proto.paralympics.content.v1.ContentModule.prototype.getVideoCover = function() {
  return /** @type{?proto.paralympics.content.v1.Image} */ (
    jspb.Message.getWrapperField(this, proto.paralympics.content.v1.Image, 16));
};


/** @param {?proto.paralympics.content.v1.Image|undefined} value */
proto.paralympics.content.v1.ContentModule.prototype.setVideoCover = function(value) {
  jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.paralympics.content.v1.ContentModule.prototype.clearVideoCover = function() {
  this.setVideoCover(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.paralympics.content.v1.ContentModule.prototype.hasVideoCover = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string video_title = 17;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getVideoTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setVideoTitle = function(value) {
  jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string dropdown_title = 18;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getDropdownTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setDropdownTitle = function(value) {
  jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string achievement_game = 19;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getAchievementGame = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setAchievementGame = function(value) {
  jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional int64 achievement_gold = 20;
 * @return {number}
 */
proto.paralympics.content.v1.ContentModule.prototype.getAchievementGold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ContentModule.prototype.setAchievementGold = function(value) {
  jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional int64 achievement_silver = 21;
 * @return {number}
 */
proto.paralympics.content.v1.ContentModule.prototype.getAchievementSilver = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ContentModule.prototype.setAchievementSilver = function(value) {
  jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional int64 achievement_bronze = 22;
 * @return {number}
 */
proto.paralympics.content.v1.ContentModule.prototype.getAchievementBronze = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ContentModule.prototype.setAchievementBronze = function(value) {
  jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional string title = 23;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string sub_title = 24;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getSubTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setSubTitle = function(value) {
  jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional string link = 25;
 * @return {string}
 */
proto.paralympics.content.v1.ContentModule.prototype.getLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.ContentModule.prototype.setLink = function(value) {
  jspb.Message.setProto3StringField(this, 25, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.paralympics.content.v1.ImageCrop.prototype.toObject = function(opt_includeInstance) {
  return proto.paralympics.content.v1.ImageCrop.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.paralympics.content.v1.ImageCrop} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.ImageCrop.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: jspb.Message.getFieldWithDefault(msg, 1, 0),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    offsetX: jspb.Message.getFieldWithDefault(msg, 3, 0),
    offsetY: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.paralympics.content.v1.ImageCrop}
 */
proto.paralympics.content.v1.ImageCrop.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.paralympics.content.v1.ImageCrop;
  return proto.paralympics.content.v1.ImageCrop.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.paralympics.content.v1.ImageCrop} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.paralympics.content.v1.ImageCrop}
 */
proto.paralympics.content.v1.ImageCrop.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWidth(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOffsetX(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOffsetY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.paralympics.content.v1.ImageCrop.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.paralympics.content.v1.ImageCrop.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.paralympics.content.v1.ImageCrop} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.ImageCrop.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getOffsetX();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getOffsetY();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 width = 1;
 * @return {number}
 */
proto.paralympics.content.v1.ImageCrop.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ImageCrop.prototype.setWidth = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 height = 2;
 * @return {number}
 */
proto.paralympics.content.v1.ImageCrop.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ImageCrop.prototype.setHeight = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 offset_x = 3;
 * @return {number}
 */
proto.paralympics.content.v1.ImageCrop.prototype.getOffsetX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ImageCrop.prototype.setOffsetX = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 offset_y = 4;
 * @return {number}
 */
proto.paralympics.content.v1.ImageCrop.prototype.getOffsetY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.paralympics.content.v1.ImageCrop.prototype.setOffsetY = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.paralympics.content.v1.Image.prototype.toObject = function(opt_includeInstance) {
  return proto.paralympics.content.v1.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.paralympics.content.v1.Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: jspb.Message.getFieldWithDefault(msg, 1, ""),
    crop: (f = msg.getCrop()) && proto.paralympics.content.v1.ImageCrop.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.paralympics.content.v1.Image}
 */
proto.paralympics.content.v1.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.paralympics.content.v1.Image;
  return proto.paralympics.content.v1.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.paralympics.content.v1.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.paralympics.content.v1.Image}
 */
proto.paralympics.content.v1.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 2:
      var value = new proto.paralympics.content.v1.ImageCrop;
      reader.readMessage(value,proto.paralympics.content.v1.ImageCrop.deserializeBinaryFromReader);
      msg.setCrop(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.paralympics.content.v1.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.paralympics.content.v1.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.paralympics.content.v1.Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.paralympics.content.v1.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCrop();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.paralympics.content.v1.ImageCrop.serializeBinaryToWriter
    );
  }
};


/**
 * optional string source = 1;
 * @return {string}
 */
proto.paralympics.content.v1.Image.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.paralympics.content.v1.Image.prototype.setSource = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ImageCrop crop = 2;
 * @return {?proto.paralympics.content.v1.ImageCrop}
 */
proto.paralympics.content.v1.Image.prototype.getCrop = function() {
  return /** @type{?proto.paralympics.content.v1.ImageCrop} */ (
    jspb.Message.getWrapperField(this, proto.paralympics.content.v1.ImageCrop, 2));
};


/** @param {?proto.paralympics.content.v1.ImageCrop|undefined} value */
proto.paralympics.content.v1.Image.prototype.setCrop = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.paralympics.content.v1.Image.prototype.clearCrop = function() {
  this.setCrop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.paralympics.content.v1.Image.prototype.hasCrop = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.paralympics.content.v1.Type = {
  TEXT: 0,
  IMAGE: 1,
  QUOTE: 2,
  HIGHLIGHT: 3,
  VIDEO: 4,
  CLASSIFICATION: 5,
  ACHIEVEMENT: 6,
  PROFILE: 7
};

goog.object.extend(exports, proto.paralympics.content.v1);
